[package]
name = "spart"
version = "0.1.0"
description = "A collection of space partitioning tree data structures for Rust."
repository = "https://github.com/habedi/spart"
license = "MIT OR Apache-2.0"
readme = "README.md"
keywords = ["quadtree", "kdtree", "r-tree", "octree", "spatial-index"]
authors = ["Hassan Abedi <hassan.abedi.t@gmail.com>"]
homepage = "https://github.com/habedi/spart"
documentation = "https://docs.rs/spart"
categories = ["data-structures", "algorithms"]
edition = "2021"

[lib]
name = "spart"
path = "src/lib.rs"

[[bin]]
name = "spart-cli"
path = "src/main.rs"

[dependencies]
clap = "4.5.27"
log = "0.4.25"
ordered-float = "4.6.0"
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
criterion = { version = "0.5", features = ["html_reports"] }

[[bench]]
name = "my_benchmark"
harness = false
